import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const AnjomanBold = localFont({
  src: "./fonts/Anjoman-Bold.woff",
  variable: "--Anjoman-Bold",
  weight: "bold",
});
const AnjomanRegular = localFont({
  src: "./fonts/Anjoman-Regular.woff",
  variable: "--Anjoman-Regular",
  weight: "normal",
});
const AnjomanLight = localFont({
  src: "./fonts/Anjoman-Light.woff",
  variable: "--Anjoman-Light",
  weight: "100",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${AnjomanBold.variable} ${AnjomanRegular.variable} ${AnjomanLight.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
